CREATE TABLE users (
                       id int generated by default as identity PRIMARY KEY,
                       nickname VARCHAR(50) UNIQUE NOT NULL,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password_hash TEXT NOT NULL,
                       created_at TIMESTAMP DEFAULT NOW(),
                       updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE refresh_tokens (
                                id int generated by default as identity PRIMARY KEY,
                                user_id INT REFERENCES users(id) ON DELETE CASCADE,
                                token TEXT NOT NULL,
                                expires_at TIMESTAMP NOT NULL,
                                created_at TIMESTAMP DEFAULT NOW()
);

