version: '3.8'

services:




  postgres:
    image: postgres:latest
    container_name: postgres_auth_service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 456456
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - postgres
    volumes:
      - ./migration:/migration
    entrypoint: [
      "/bin/sh", "-c",
      "sleep 5 && migrate -path=/migration -database postgres://admin:456456@postgres:5432/auth_db?sslmode=disable up"
    ]







volumes:
  postgres_data:
